### ISSUE TITLE
Feature Request: more verbose name for OP code variables

### ISSUE THREAD

**Issue by Arignir** [hank-der-hafenarbeiter/imperative-rs#1]
I'm trying out `imperative-rs` for a personal project of mine, and I find it quite sad that we can only name the OP code variables using one letter. It isn't very verbose and doesn't help make the code more clear.

I understand the need to use one-char symbols when detailing the op code structure, I just find it inconvenient that such restriction also applies to the name of the enum members.

Would it be possible to extend `imperative-rs` with an additional macro that let the user choose the character-representation of any variables for an opcode, therefore releasing the naming constraint of the enum members?

Something among the lines of 

```rust
#[derive(InstructionSet)]
enum Is {
    //constant opcode
    #[opcode = "0b00000000"]
    Nop,
    #[opcode = "0b10xxxyyy"]
    Mov {
        #[variable = "x"]
        Rhs: u8,
        #[variable = "y"]
        Lhs: i8
    },
}
```

Thank you very much for hearing me out!

**Comment by hank-der-hafenarbeiter** [comment]
Hey Arignir,

this seems like a very reasonable request and a very promising sketch of an implementation.

I can't promise when I'll get to it, but it's definitely something I want the crate to be able to do.

Thanks for your input.

**Comment by hank-der-hafenarbeiter** [comment]
That was easier than expected. Version 0.1.4 supports this feature (though I probably should bump it up to 0.2 I guess). It's getting late here so I just implemented it and tested it with one example. No tests yet, so don't expect it to work flawlessly.

**Comment by Arignir** [comment]
Version `0.1.4` uses the unstable `peekable_next_if` feature. Was that intentional?

**Comment by hank-der-hafenarbeiter** [comment]
This is actually part of another update I implemented today. Before when decoding messages from `&[u8]` the code generated by the macro would extract every bit separately, shift them to the right place and `|` them all together. Now the macro peeks if the next bit is next to the current one and if so it adds it to the "extraction block" so to say. So if all bits of a byte are of the same variable it's one bitwise-and and no bitewise-or whereas before it was 8 `&` and 8 `|`. I wanted to get it done and this feature is just perfect for it, but since I can't sleep I might replace it with something more stable.

**Comment by hank-der-hafenarbeiter** [comment]
There we go.

**Comment by Arignir** [comment]
I got a chance to try it out yesterday and everything looks good to me! Thanks! 👌
