### ISSUE TITLE
`bool` cannot be used as a target type.

### ISSUE THREAD

**Issue by Arignir** [hank-der-hafenarbeiter/imperative-rs#3]
If `bool` is used as a target type, the following errors is prompted at compilation:

```
error[E0369]: no implementation for `&bool >> usize`
   --> src\core\arm\isa.rs:4:10
    |
4   | #[derive(InstructionSet, Copy, Clone, Eq, PartialEq, Hash, Debug)]
    |          ^^^^^^^^^^^^^^ usize
...
273 |         link: bool,  // Link
    |         ---- &bool
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is that intended?

As a user I would expect bool to work out of the box, and I guess the current implementation uses the `>>` operator which isn't define for `bool` so I'm not sure if there's any quick solution to this issue, but just in case i'm posting it.

Thank you for your time,
Arignir

**Comment by hank-der-hafenarbeiter** [comment]
Hey Arignir,

it's not "intended" as much as it's not implemented yet. I think your guess for why it doesn't work is spot on. But I also think this is indicative of a bigger design flaw: The bit shifting shouldn't be done in the target type because it is error prone and restrictive. The target type needs to define `<<`, `>>` and probably `|` and `&` as well. Additionally these operators would need to show the correct behaviour. Ideally the target type would only need to support `into<u8>` and `from<u8>`.

I have an eventful week ahead, so I might not be able to look into it until the weekend. If you want to take a crack at it, I'd encourage it.

Regards,
Hank

**Comment by hank-der-hafenarbeiter** [comment]
I just pushed a commit that implements `bool` variables. For the moment when encoding instructions, the proc macro will set the least significant bit belonging to the variable in each byte to one, when the variable is true.
```rust
#[derive(InstructionSet)]
enum Is {
    #[opcode="0x0v_0v_v0"]
    A{v:bool}, //encodes into 0x01_01_10 if v is true
    #[opcode="0x00_vv_v0"]
    B{v:bool}, //encodes into 0x00_01_10 if v is true
}
```

Currently I would specify the behaviour loosely and say "When the boolean is true the encoder will set at least one bit to 1". Later I might add the option to set all corresponding bits to 1 if the boolean is true, should the need arise.

Any thoughts on this?

**Comment by Arignir** [comment]
If I were you, I would throw a compile-time error if the value cannot be safely represented, like if there's more than one letter for a `bool` variable, or more than 8 for an `u8` variable, etc.

That's what I would have naturally expected, at least, but maybe there's some benefits with your implementation that I'm missing?

**Comment by hank-der-hafenarbeiter** [comment]
So far I tried to avoid hardcoding stuff for particular types, because it would be great to make this usable for all types that implement `into<u8>` and `from<u8>`. But I think the moment to stray from this idea has come. It makes a lot of sense to make it work perfectly for the integer types and if that causes extra work should this ever be opened up to other types: So be it.

Busy week again, also probably a busy weekend. I don't know when I'll come to it.

You seem to be working on a project using this. If it gets to a working state and you are willing, it would be great to have some example projects in an `examples` folder, yours could be the first!

**Comment by Arignir** [comment]
Thanks! I'm mostly experimenting as of now, not sure if what I'm doing will end anywhere :')

**Comment by hank-der-hafenarbeiter** [comment]
I hope it will!

Anyway, new version is on crates.io (and this repository). Version 0.3.0 works the way we discussed here.

I'm closing this for now. If you encounter any problems either come here or just open a new issue. It's not like there is a flood of them anyway.

Have fun

**Comment by Arignir** [comment]
Thank you very much 👍
